// Flattens the Figma-exported DTCG token files into CSS custom properties.
// Run with `npm run tokens` after re-exporting Light.tokens.json / Dark.tokens.json.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(root, 'client', 'src', 'styles', 'tokens.css');

const slug = (parts) =>
  parts
    .join('-')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

function flatten(node, path = [], acc = {}) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (value && typeof value === 'object' && value.$value !== undefined) {
      acc[slug([...path, key])] = { raw: value.$value, path: [...path, key] };
    } else if (value && typeof value === 'object') {
      flatten(value, [...path, key], acc);
    }
  }
  return acc;
}

function toCss(raw, table) {
  if (typeof raw === 'string') {
    const alias = raw.match(/^\{(.+)\}$/);
    if (!alias) return null;
    const target = slug(alias[1].split('.'));
    return table[target] ? `var(--${target})` : null;
  }
  const { components, alpha, hex } = raw;
  if (alpha !== undefined && alpha < 1 && components) {
    const [r, g, b] = components.map((c) => Math.round(c * 255));
    return `rgb(${r} ${g} ${b} / ${Number(alpha.toFixed(3))})`;
  }
  return hex ? hex.toLowerCase() : null;
}

function declarations(file) {
  const table = flatten(JSON.parse(readFileSync(join(root, 'design-tokens', file), 'utf8')));
  return Object.entries(table)
    .map(([name, token]) => {
      const value = toCss(token.raw, table);
      return value ? `  --${name}: ${value};` : null;
    })
    .filter(Boolean)
    .join('\n');
}

const css = `/* Generated by scripts/build-tokens.mjs — do not edit by hand. */
:root {
${declarations('Light.tokens.json')}
}

:root[data-theme='dark'] {
${declarations('Dark.tokens.json')}
}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, css);
console.log(`tokens → ${outFile}`);
